### PR TITLE
Delete customer and delete all customers

### PR DESCRIPTION
**Pull request by jonnii**
I've added a feature branch for deleting customers.  

I'm not sure what the API returns when you delete a customer, probably the customer record before deletion.  

For delete-all it probably returns every customer... who knows, I don't have an environment to try it on.

### CODE REVIEW

**Comment by blaix** [comment]
Since we're not using this library and don't have time to maintain it, I'd like to update our repo and README to link to yours as the new official fork. Would that be ok?

**Comment by jonnii** [comment]
Sure, alternatively you can give me commit writes to your repo.  Thoughts?

**Comment by blaix** [comment]
That works too. I'll ping the repo's admin.

**Comment by blaix** [comment]
You're added. Go nuts :)

**Comment by charliezhao** [comment]
Jonnii,

Where is your branch which has deleting customers? I do not see it here,

Thanks

**Comment by jonnii** [comment]
You can get my private gem before I get around to releasing an official one:  jonnii-cheddargetter

**Pull request merged**
